spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  profiles:
    include: local
#    include: dev

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


